<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPWZ0vOL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPWZ0vOL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerPWZ0vOL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerPWZ0vOL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerPWZ0vOL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'PWZ0vOL',
    'container.build_id' => '54c34f73',
    'container.build_time' => 1556900714,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPWZ0vOL');
